Repository Groupify-SCE/AlgorithmsPlayground, pull requests merged in 2024-12, with the labels that each got.

#1 Create cicd.yml
  .github/workflows/cicd.yml
Labels: DevOps

#2 Added CI/CD Process
  .github/workflows/cicd.yml
Labels: DevOps

#3 Feature/setup main and input
  helperFunctions.py
  main.py
  requirements.txt
  student.py
Labels: New Feature

#4 Feature/standard genetic algorithm
  Genetic/StandardGenetic.py
  main.py
  utils/helperFunctions.py
  utils/student.py
Labels: New Feature

#6 Added shuffle students list on initial groups
  Genetic/PreferencesGenetic.py
Labels: Improvement

#7 Feature/samples setup
  main.py
  samples/students(10)_criteria(3).json
  samples/students(15)_criteria(1).json
  samples/students(50)_criteria(2).json
  utils/helperFunctions.py
Labels: New Feature, Improvement
