Repository Groupify-SCE/AlgorithmsPlayground, pull requests merged in 2025-01, with the labels that each got.

#8 Feature/add experiments
  Genetic/PreferencesGenetic.py
  experiments/generations_experiment.csv
  experiments/mutation_experiment.csv
  experiments/mutation_timing_experiment.csv
  experiments/population_experiment.csv
  experiments/population_timing_experiment.csv
  experiments/timing_experiment.csv
  main.py
  samples/students(200)_criteria(5).json
  utils/helperFunctions.py
Labels: Documentation, New Feature

#9 Finished the first version of the Genetic Algorithm
  .gitignore
  Genetic/PreferencesGenetic.py
  Genetic/StandardGenetic.py
  experiments/generations_experiment.csv
  experiments/mutation_experiment.csv
  experiments/mutation_timing_experiment.csv
  experiments/population_experiment.csv
  experiments/population_timing_experiment.csv
  experiments/timing_experiment.csv
  main.py
  requirements.txt
  samples/students(10)_criteria(3).json
  samples/students(15)_criteria(1).json
  samples/students(200)_criteria(5).json
  samples/students(50)_criteria(2).json
  utils/helperFunctions.py
  utils/student.py
Labels: New Feature

#10 Added pytest to requirements.txt
  requirements.txt
Labels: Bug

#11 Created a dummy test
  tests/test_genetic.py
Labels: Bug

#12 Finished Version 1.0.0 with Genetic Algorithm Done
  .github/workflows/cicd.yml
  .gitignore
  Genetic/PreferencesGenetic.py
  Genetic/StandardGenetic.py
  experiments/generations_experiment.csv
  experiments/mutation_experiment.csv
  experiments/mutation_timing_experiment.csv
  experiments/population_experiment.csv
  experiments/population_timing_experiment.csv
  experiments/timing_experiment.csv
  main.py
  requirements.txt
  samples/students(10)_criteria(3).json
  samples/students(15)_criteria(1).json
  samples/students(200)_criteria(5).json
  samples/students(50)_criteria(2).json
  tests/test_genetic.py
  utils/helperFunctions.py
  utils/student.py
Labels: New Feature

#13 Finished writing Bee Colony algorithm.
  ABC/StandardABC.py
  main.py
Labels: New Feature

#14 Finished the bees algorithm with personal preferences
  ABC/PrefrencesABC.py
  main.py
Labels: New Feature, Improvement

#15 The ABC Algorithm is Finished
  ABC/PrefrencesABC.py
  ABC/StandardABC.py
  main.py
Labels: New Feature

#16 Finished V2.0.0
  ABC/PrefrencesABC.py
  ABC/StandardABC.py
  main.py
Labels: New Feature

#17 Feature/new experiments to ne initial division
  ABC/PrefrencesABC.py
  ABC/StandardABC.py
  Genetic/PreferencesGenetic.py
  Genetic/StandardGenetic.py
  experiments/ABC/Iterations_Fitness.csv
  experiments/ABC/Iterations_Time.csv
  experiments/data/RanInt_n060_ss_01.txt
  experiments/data/acceptance60_1.txt
  main.py
  requirements.txt
  utils/experimentsFunctions.py
  utils/helperFunctions.py
  utils/student.py
Labels: Improvement
